export interface Project {
	id: number;
	title: string;
	description: string;
	image: string;
	technologies: string[];
	category: string;
	liveUrl: string;
	githubUrl: string;
}
export const projects: Array<Project> = [
	{
		id: 1,
		title: 'Student Name Parser',
		description:
			'A specialized tool for extracting students name coming from pdf generated by our schools old registrar system, and Transform them into a ready made excel file for class records.',
		image: '/images/student-name-parser.png',
		technologies: ['HTML', 'CSS', 'Python', 'Flask'],
		category: 'Full Stack',
		liveUrl: 'https://oninsan.github.io/LFM_Separator_frontend/',
		githubUrl: 'https://github.com/oninsan/LFM_Separator_frontend'
	},
	{
		id: 2,
		title: 'Resume Maker',
		description:
			'A specialized tool for creating personalized CV or Resume. It has a seamless way of adding different sections in a CV.',
		image: '/images/resume-maker.png',
		technologies: ['HTML', 'CSS', 'PHP', 'SQL'],
		category: 'Full Stack',
		liveUrl: '#',
		githubUrl: 'https://gitlab.com/oninsama/resume-maker/-/tree/master?ref_type=heads'
	},
	{
		id: 3,
		title: 'OALM - Online Archive of Learning Materials',
		description:
			'An online repository for learning materials built for CRMC. It can store and create materials for teachers, and allow students view and download thos materials',
		image: '/images/lm-archive.png',
		technologies: ['MongoDb', 'Express', 'React', 'NodeJs'],
		category: 'React',
		liveUrl: '#',
		githubUrl: 'https://gitlab.com/oninsama/onlinarchiveforlearningmaterials'
	},
	{
		id: 4,
		title: 'ChitChat',
		description:
			'A fast, safe messaging app that employs 3-way encryption. Currently in progress and still in the process of implementing some UI. I am halfway done with the backend.',
		image: '/images/chitchat.png',
		technologies: ['Mysql', 'Dotnet', 'Svelte'],
		category: 'Svelte',
		liveUrl: '#',
		githubUrl: '#'
	},
	{
		id: 5,
		title: 'DevPortfolio',
		description:
			'My personal portfolio app that showcases my latest project. It also has my public information for the clients to reachout me whenever they want.',
		image: '/images/devPortfolio.png',
		technologies: ['Svelte'],
		category: 'Svelte',
		liveUrl: '#',
		githubUrl: 'https://github.com/oninsan/Portfolio'
	}
];
