<script lang="ts">
	import { onMount } from 'svelte';
	import Card from './ui/Card.svelte';
	import Badge from './ui/Badge.svelte';
	import { ExternalLink, Github, Eye } from 'lucide-svelte';
  import studentParser from '$lib/assets/images/student-name-parser.png';
  import resumeMaker from '$lib/assets/images/resume-maker.png';
  import oalm from '$lib/assets/images/lm-archive.png'
  import chitchat from '$lib/assets/images/chitchat.png'
  import devPortfolio from '$lib/assets/images/devPortfolio.png'
	
	let projectsElement:Element;
	let activeFilter = 'All';
	
	const filters = ['All', 'React', 'Svelte', 'Full Stack'];
	
	const projects = [
    {
			id: 1,
			title: 'Student Name Parser',
			description: 'A specialized tool for extracting students name coming from pdf generated by our schools old registrar system, and Transform them into a ready made excel file for class records.',
			image: studentParser,
			technologies: ['HTML', 'CSS', 'Python', 'Flask'],
			category: 'Full Stack',
			liveUrl: 'https://oninsan.github.io/LFM_Separator_frontend/',
			githubUrl: 'https://github.com/oninsan/LFM_Separator_frontend'
		},
    {
			id: 2,
			title: 'Resume Maker',
			description: 'A specialized tool for creating personalized CV or Resume. It has a seamless way of adding different sections in a CV.',
			image: resumeMaker,
			technologies: ['HTML', 'CSS', 'PHP', 'SQL'],
			category: 'Full Stack',
			liveUrl: '#',
			githubUrl: 'https://gitlab.com/oninsama/resume-maker/-/tree/master?ref_type=heads'
		},
    {
			id: 3,
			title: 'OALM - Online Archive of Learning Materials',
			description: 'An online repository for learning materials built for CRMC. It can store and create materials for teachers, and allow students view and download thos materials',
			image: oalm,
			technologies: ['MongoDb', 'Express', 'React', 'NodeJs'],
			category: 'React',
			liveUrl: '#',
			githubUrl: 'https://gitlab.com/oninsama/onlinarchiveforlearningmaterials'
		},
    {
			id: 4,
			title: 'ChitChat',
			description: 'A fast, safe messaging app that employs 3-way encryption. Currently in progress and still in the process of implementing some UI. I am halfway done with the backend.',
			image: chitchat,
			technologies: ['Mysql', 'Dotnet', 'Svelte'],
			category: 'Svelte',
			liveUrl: '#',
			githubUrl: '#'
		},
    {
			id: 5,
			title: 'DevPortfolio',
			description: 'My personal portfolio app that showcases my latest project. It also has my public information for the clients to reachout me whenever they want.',
			image: devPortfolio,
			technologies: ['Svelte'],
			category: 'Svelte',
			liveUrl: '#',
			githubUrl: 'https://github.com/oninsan/Portfolio'
		},
	];
	
	$: filteredProjects = activeFilter === 'All' 
		? projects 
		: projects.filter(project => project.category === activeFilter);
	
	onMount(() => {
		const observer = new IntersectionObserver((entries) => {
			entries.forEach((entry) => {
				if (entry.isIntersecting) {
					entry.target.classList.add('animate-projects');
				}
			});
		});
		
		if (projectsElement) observer.observe(projectsElement);
		
		return () => observer.disconnect();
	});
</script>

<section id="projects" class="py-20 bg-gray-50" bind:this={projectsElement}>
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
		<div class="text-center mb-16">
			<h2 class="text-4xl md:text-5xl font-bold text-gray-900 mb-4">Featured Projects</h2>
			<div class="w-24 h-1 bg-primary mx-auto mb-6"></div>
			<p class="text-gray-600 max-w-3xl mx-auto text-lg">
				Here are some of my recent projects that showcase my skills and experience
			</p>
		</div>

		<!-- Filter Buttons -->
		<div class="flex flex-wrap justify-center gap-4 mb-12">
			{#each filters as filter}
				<button
					on:click={() => activeFilter = filter}
					class="px-6 py-2 rounded-full font-medium transition-all duration-300
						{activeFilter === filter 
							? 'bg-primary text-white shadow-lg' 
							: 'bg-white text-gray-600 hover:bg-primary hover:text-white shadow-md'}"
				>
					{filter}
				</button>
			{/each}
		</div>

		<!-- Projects Grid -->
		<div class="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
			{#each filteredProjects as project, index (project.id)}
				<Card className="group overflow-hidden hover:shadow-2xl transition-all duration-500 hover:-translate-y-2 project-card">
					<!-- Project Image -->
					<div class="relative overflow-hidden">
						<img 
							src={project.image} 
							alt={project.title}
							class="w-full h-48 object-cover group-hover:scale-110 transition-transform duration-500"
						/>
						<div class="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300">
							<div class="absolute bottom-4 left-4 right-4 flex justify-between">
								<a 
									href={project.liveUrl} 
									target="_blank" 
									rel="noopener noreferrer"
									class="bg-white text-gray-900 p-2 rounded-full hover:bg-primary hover:text-white transition-colors duration-200"
								>
									<Eye class="h-4 w-4" />
								</a>
								<a 
									href={project.githubUrl} 
									target="_blank" 
									rel="noopener noreferrer"
									class="bg-white text-gray-900 p-2 rounded-full hover:bg-primary hover:text-white transition-colors duration-200"
								>
									<Github class="h-4 w-4" />
								</a>
								<a 
									href={project.liveUrl} 
									target="_blank" 
									rel="noopener noreferrer"
									class="bg-white text-gray-900 p-2 rounded-full hover:bg-primary hover:text-white transition-colors duration-200"
								>
									<ExternalLink class="h-4 w-4" />
								</a>
							</div>
						</div>
					</div>

					<!-- Project Details -->
					<div class="p-6">
						<h3 class="text-xl font-bold text-gray-900 mb-2 group-hover:text-primary transition-colors duration-200">
							{project.title}
						</h3>
						<p class="text-gray-600 text-sm mb-4 leading-relaxed">
							{project.description}
						</p>

						<!-- Technologies -->
						<div class="flex flex-wrap gap-2 mb-4">
							{#each project.technologies as tech}
								<Badge variant="secondary" className="text-xs">
									{tech}
								</Badge>
							{/each}
						</div>

						<!-- Links -->
						<div class="flex space-x-4">
							<a 
								href={project.liveUrl} 
								target="_blank" 
								rel="noopener noreferrer"
								class="flex-1 bg-primary hover:bg-primary/90 text-white text-center py-2 px-4 rounded-lg font-medium transition-colors duration-200 text-sm"
							>
								Live Demo
							</a>
							<a 
								href={project.githubUrl} 
								target="_blank" 
								rel="noopener noreferrer"
								class="bg-gray-200 hover:bg-gray-300 text-gray-700 py-2 px-4 rounded-lg font-medium transition-colors duration-200 text-sm"
							>
								Code
							</a>
						</div>
					</div>
				</Card>
			{/each}
		</div>

		{#if filteredProjects.length === 0}
			<div class="text-center py-16">
				<p class="text-gray-500 text-lg">No projects found for the selected filter.</p>
			</div>
		{/if}
	</div>
</section>

<style>
	@keyframes fade-in-scale {
		from { 
			opacity: 0; 
			transform: translateY(30px) scale(0.95); 
		}
		to { 
			opacity: 1; 
			transform: translateY(0) scale(1); 
		}
	}
	
	.animate-projects .project-card {
		animation: fade-in-scale 0.6s ease-out both;
	}
</style>